# Generated by Django 3.0.4 on 2020-03-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('preco', models.IntegerField()),
                ('status', models.CharField(choices=[('Acessivel', 'Item pronto para venda'), ('Vendido', 'Item Vendido'), ('Abastecimento', 'Item para repor nos proximos dias')], default='Vendido', max_length=100)),
                ('issues', models.CharField(default='Sem problemas', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Computadores',
        ),
    ]
