# Generated by Django 3.0.4 on 2020-03-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200328_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'Item pronto para venda'), ('Vendido', 'Item Vendido'), ('Abastecimento', 'Item para repor nos proximos dias')], default='Vendido', max_length=100),
        ),
        migrations.AlterField(
            model_name='computador',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'Item pronto para venda'), ('Vendido', 'Item Vendido'), ('Abastecimento', 'Item para repor nos proximos dias')], default='Vendido', max_length=100),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'Item pronto para venda'), ('Vendido', 'Item Vendido'), ('Abastecimento', 'Item para repor nos proximos dias')], default='Vendido', max_length=100),
        ),
    ]
